name: ledgai-quantconnect-mcp
region: nyc
services:
- name: mcp-server
  dockerfile_path: Dockerfile.jwt
  source_dir: .
  github:
    repo: i-dream-of-ai/quantconnect-mcp-fork
    branch: main
    deploy_on_push: true
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: ENABLE_AUTH
    value: "true"
    scope: RUN_TIME
  - key: PYTHONPATH
    value: "/app/src"
    scope: RUN_TIME
  - key: JWT_SECRET_KEY
    value: "dev-secret-key-change-in-production"
    scope: RUN_TIME
  - key: QUANTCONNECT_USER_ID
    value: "406922"
    scope: RUN_TIME
  - key: QUANTCONNECT_TOKEN
    value: "428ff4953fc81908d3816549d6d65c8910032b111159b7cdb5b03c829713724d"
    scope: RUN_TIME
  - key: QUANTCONNECT_ORGANIZATION_ID
    value: "c6880779be8442f9147fd531ddc7bc75"
    scope: RUN_TIME